package entity;

public enum Command {
    START, SETADMINNAME, REGISTRATION, SETUSERNAME, SETROLE, SETGROUP, SETREPORT, GETALLUSER, GETUSERBYCHATID,
    UPDATEUSER, DELETEUSER;
    Command() {
    }
}
