package entity;

public enum Command {
    START, SETADMINNAME, REGISTRATION, SETUSERNAME, SETROLE, SETGROUP, SETREPORT, GETALLUSER, GETUSERBYCHATID,
    UPDATEUSERNAME, UPDATEUSERGROUP, DELETEUSER;

    Command() {
    }
}
